<?php

namespace YoRenard\PimpMyQueryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PMQFavoriteQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PMQFavoriteQueryRepository extends EntityRepository
{
}